### ISSUE TITLE
Errno=23

### ISSUE THREAD

**Issue by BbIKTOP** [Mixiaoxiao/Arduino-HomeKit-ESP#3]
Hi again!

Thank you for your port. Looking at your sources, I realise that you probably aware of this problem, so this issue I opened, is just to clarify have you found a solution or not. 
In brief: i’ve made a simple program with hap switch and a WebServer. WebServer serves the site with the content located on the littlefs partition with streamFile call. It opens requested file, streams it to the client, then closes it.
When used with esp hap, it leads to the errno 23 after a few minutes of inactivity. I mean, external inactivity, like, no http queries, hap is working in the background. Then, after 15-30 minutes, each lwip accept call in the WebServer fails with errno 23. Hap is still working for a while, but also fails then, when i try to reconnect the client (like, rebooting iphone and relaunching its home.app)
My question is: are you really aware of that? I see a piece of “workaround” code in your sources, where you’re trying to close control connections. Looks like it doesn’t fix it completely, I suppose it just postphones the problem, and webserver usage just makes it visible quicker. 
the same code without hap works fine for hours of course, which makes me think that there’s some “sockets leak” inside espressif hap. Do you have any ideas?
Thank you!

**Comment by Mixiaoxiao** [comment]
I meet this issue with the esp32 arduino based on idf-3.2. When I use idf-4.2, all things are good.

**Comment by BbIKTOP** [comment]
Well, thank you! Do you have an idea how to update it using PIO? I have latest and it comes with v3.3.5-1-g85c43024c

**Comment by BbIKTOP** [comment]
Ok, updated to the new version:

```
platform =https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
board = esp32dev
framework = arduino
platform_packages =
   	framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#2.0.0
```

Now have this:
```
/Users/viktor/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: 
/Users/viktor/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/lib/libmbedcrypto.a(esp_bignum.c.obj): 
in function `esp_mpi_mul_mpi_mod':
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/mbedtls/port/esp_bignum.c:149: 
multiple definition of `esp_mpi_mul_mpi_mod'; .pio/build/esp32dev/lib5d2/libArduino-HomeKit-ESP.a(esp_bignum.c.o):
/Volumes/Projects Sources/Arduino/HomeAutomator/lib/Arduino-HomeKit-ESP/src/port/esp_bignum.c:153: first defined here

/Users/viktor/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: 
/Users/viktor/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/lib/libmbedcrypto.a(esp_bignum.c.obj): 
in function `mbedtls_mpi_mul_mpi':
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/mbedtls/port/esp_bignum.c:365: 
multiple definition of `mbedtls_mpi_mul_mpi'; .pio/build/esp32dev/lib5d2/libArduino-HomeKit-ESP.a(esp_bignum.c.o):
/Volumes/Projects Sources/Arduino/HomeAutomator/lib/Arduino-HomeKit-ESP/src/port/esp_bignum.c:372: first defined here
```

Looks like these 2 foos are already implemented. Comented out both, is it ok? Everything is working so far, will leave it for a while then report back.

**Comment by BbIKTOP** [comment]
Well, with the new core and toolchain I've got the same result but much faster! )) Just in a minute or two.

**Comment by BbIKTOP** [comment]
Ok, found the reason. The default amount of sockets in the arduino is 10. TEN!!!! Even in the 4+. In the device that primarily positioned as "network" )))) So, as I have 6 clients connected, and arduino's WiFiServer consumes 4 sockets just for a start, there's no more sockets left after that. Sorry, I disturbed you, hope that probably it would be interesting for you to be aware of that as well.

Update: also changed ``#define CONFIG_HAP_HTTP_MAX_OPEN_SOCKETS 12``
